//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration___Login_Desktop_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINE
    {
        public int ADMINN_ID { get; set; }
        public string ADMINN_NAME { get; set; }
        public string ADMINN_PASS { get; set; }
    }
}
