//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration___Login_Desktop_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERR
    {
        public int USERRID { get; set; }
        public string USERRNAME { get; set; }
        public string PASSWORDD { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> AGE { get; set; }
        public string phonenumber { get; set; }
        public string CITY { get; set; }
    }
}
